### ISSUE TITLE
Applying both Multiplatform and Android library plugin skips multiplatform source sets

### ISSUE THREAD

**Issue by Daio-io** [tylerbwong/metalava-gradle#104]
We recently started looking at using [v0.4.0 alpha](https://github.com/tylerbwong/metalava-gradle/releases/tag/0.4.0-alpha01) to support the removal of test sources from the output but I noticed that when applying both multiplatform and Android library plugins, multiplatform source sets are ignored because Android is checked first meaning you get no output from multiplatform main modules.

We could set to support the `additionalSourceSets` but it would be useful to check if multiple extensions are applied then it should generate sources for those modules too.

Sorry I do not have an example to share, Its a work project but I can share one when I get chance after work, although hopefully enough here to understand the issue.

**Comment by tylerbwong** [comment]
Hey @Daio-io, sorry for the late reply! Thanks for the report. This should be fixed by #106.

**Comment by Daio-io** [comment]
Awesome! Thanks @tylerbwong

**Comment by tylerbwong** [comment]
@Daio-io Just published `0.4.0-alpha02`! Let me know if it works.
