### ISSUE TITLE
Do not throw exceptions for unsupported modules

### ISSUE THREAD

**Issue by RinOrz** [tylerbwong/metalava-gradle#22]
Sometimes I will apply metalava through `allprojects`, but some projects are not supported, I hope this can ignore them through a boolean instead of directly throwing an exception.

**Comment by tylerbwong** [comment]
Hi @RinOrz! Thanks for checking out this plugin. I saw in #23 that you added a configurable flag to suppress the exception, but I was wondering, maybe it should be the default behavior for the plugin to only report a warning in this case.

What kind of Gradle projects of yours are not supported? I would also like to see if we can add support for these.

**Comment by RinOrz** [comment]
@tylerbwong Just like root project, it just does not apply any plugins

**Comment by RinOrz** [comment]
> only report a warning

I agree with this!

**Comment by tylerbwong** [comment]
Sounds good. Let's remove the flag and have the plugin report errors by default 👍

**Comment by tylerbwong** [comment]
Fixed in 44f8fee95a28561736088f1668682fd05c729a31
