### ISSUE TITLE
Java test classes are not ignored in 0.2.0

### ISSUE THREAD

**Issue by pavelreiter** [tylerbwong/metalava-gradle#27]
I have multimodule android project with library module which is mix of Kotlin and Java classes.
After update from 0.1.9 to 0.2.0 I have encountered issue that single Java test class is now being picked up as part of api and metalava check task fails.

I have tried adding used test annotations to hiddenAnnoation list but that also didn't help.

For now my workaround is to lower visibility of the test class.

**Comment by pavelreiter** [comment]
It appears to be that this issue is on metalava side. Other possible workaround is also to convert the Java test class to Kotlin.

**Comment by tylerbwong** [comment]
Hey @pavelreiter, thanks for the bug report. I believe this actually was an issue that was introduced in 0.2.0 and I have pushed a fix. 0.2.1 will be released shortly!
