### ISSUE TITLE
0.3.0: android.jar classpath seems to be missing

### ISSUE THREAD

**Issue by herriojr** [tylerbwong/metalava-gradle#49]
I don't know what changed exactly in 0.3.0, but if I don't explicitly add the android.jar classpath (and run the metalava command manually), I get a lot of issues in both the signature generation such as:

src/main/my/package/MyClass.java:5: info: Unresolved import: `android.text.TextUtils` [UnresolvedImport]

Unfortunately, this causes the signature to be generated improperly and breaks everything.

I've attempted reproducing this with one of the samples in this repository. I don't get the same exact error, however, I do get the following generation for the android-groovy if I use an Android class:

```
package me.tylerbwong.gradle.metalava.sample

import android.text.TextUtils
import java.io.IOException
import java.util.*

interface SamplePublicApi {
    val publicApiProperty: String
    fun publicApiFunction()
    @Throws(IOException::class)
    fun test(list: ArrayList<String>)
    fun test2(test: TextUtils)
}
```

generates:

```
// Signature format: 4.0
package me.tylerbwong.gradle.metalava.sample {

  public interface SamplePublicApi {
    method public String getPublicApiProperty();
    method public void publicApiFunction();
    method @kotlin.jvm.Throws(exceptionClasses=IOException::class) public void test(java.util.ArrayList<java.lang.String> list);
    method public void test2(error.NonExistentClass test);
    property public abstract String publicApiProperty;
  }

}
```

Edit: It appears the bootClassPath needs to be added to the compileClassPath.

**Comment by herriojr** [comment]
@tylerbwong I created a patch for this that I've verified to work that just needs to be merged. I guess after a version bump will be required.

**Comment by tylerbwong** [comment]
Thanks so much for catching this! I'll release 0.3.1 shortly.
