### ISSUE TITLE
Configuration is unacceptably slow

### ISSUE THREAD

**Issue by jhansche** [tylerbwong/metalava-gradle#53]
When the `metalava` plugin is applied, configuration of projects takes an absurd amount of time (usually between 30 seconds and 2 minutes). Configuration is meant to be fast and should not be this slow - since the task execution should be where the majority of time is spent.

The problem is not isolated to other projects: in fact, the same thing happens _in this very project_. All you have to do is run `./gradlew clean && ./gradlew clean` back to back, and you can see the slow configuration times. In my case (with this project), I saw the first clean take `5m 58s` (understandable, as it was downloading dependencies, etc); and the 2nd clean with no modifications took `1m 55s`. Since there was no change between those commands, and I was only running `clean`, there's no reason this should take so long.

Running a build scan shows that the time is spent in Model Configuration, and specifically in creating the 2 tasks.

It looks like there are a number of things that could be improved here:

1. Task creation should use tasks.register() instead of tasks.create().
2. Anything resolving project files should be applied using Provider or Property instead of materializing the value during configuration

In troubleshooting this and adding some timestamp breadcrumbs:
* `MetalavaGenerateSignatureTask` configuration takes 17 seconds
* `MetalavaCheckCompatibilityTask` configuration takes 15 seconds

The culprit ends up being `module.bootClasspath`, which for the Java module, has to scan multiple directories. I didn't dig into why it takes so long, but what I can do is move that work to happen only at task execution time (when the Provider is read). However, it would also be great to figure out why this bootClasspath takes so long to calculate, and if there's a more appropriate way to address it.

Before my changes (if you run a build scan on metalava project today, running only ":plugin:tasks" task):
* `gradlew tasks`: https://scans.gradle.com/s/tvha27uguhq5w/performance/configuration
  * 2 tasks created immediately
  * 1 task (check) created during configuration, by the plugin - due to tasks.findByName("check")
  * 42 seconds spent in Model Configuration and 1st afterEvaluate
* `gradlew metalavaGen`: https://scans.gradle.com/s/ttufjgxpjhe3s/performance/build
  * takes 38 seconds:
  * 30 seconds in configuration
  * 7 seconds in task execution

After my changes:
* `gradlew tasks`: https://scans.gradle.com/s/5xl2hhhjberkk/performance/configuration
  * 0 tasks created immediately
  * Plugin does not create any additional tasks during configuration - due to switching to tasks.named("check")
  * 0.9 seconds spent in Model Configuration and afterEvaluate
* `gradlew metalavaGen`: https://scans.gradle.com/s/iejkcx2uhzbfe/performance/build
  * takes 40 seconds:
  * 16 seconds in configuration (calculating task graph)
  * 24 seconds executing the metalava task

It does cause the task itself to take longer, because now the bootClasspath is calculated during task execution instead of during configuration. But the **critical** thing to consider here, is that this bootClasspath no longer holds up every single execution of `gradlew` (including `help`, `:tasks`, `:clean`, and everything else non-Metalava related), and instead only affects the Metalava tasks specifically. And that is a significant improvement.

I'll submit my PR momentarily - just running final checks

**Comment by jhansche** [comment]
I just realized the Java module is doing a full directory scan of `java.home`/`JAVA_HOME`, looking for the `rt.jar` file. However, when executing in a Java 11 JVM, there is no rt.jar. So this is doing a full, recursive, depth-first directory scan of the entire java home path, looking for a file it would never find!

This could be handled easily by scanning for rt.jar only if the JDK version is < 11. Or by giving it a fixed path (`"${JAVA_HOME}/jre/lib/rt.jar"`) and taking that only if it exists.

However, the #54 PR will still be good for configuration caching and just general good Gradle-plugin etiquette. Fixing the rt.jar issue would not be a good long-term solution to this problem - that would just be another improvement.

**Comment by jhansche** [comment]
Well, now I'm not entirely sure that the rt.jar issue is specifically a Java 11 problem.

When I scan the Java 8 home, I get 1661 files.

When I scan my Java 11 home (openjdk@11 from Homebrew), I get over 250k files. Looking into that, it appears that at some point someone or something set the GRADLE_USER_HOME directory to the JAVA_HOME directory, so there are Gradle wrapper dists and Gradle caches in that directory, along with everything else you'd expect to find in ~/.gradle, which obviously don't belong there. This appears to be the reason that scanning for `rt.jar` takes so long, because it does take a long time to scan 250k files (doing `find $JAVA_HOME | wc -l` also takes around 15 seconds in this state).

So I don't think this is a major issue impacting everyone, but it still seems to be unnecessary. If you'd like I can undo the Module.kt changes in that PR, since it likely isn't an issue when JAVA_HOME is kept in its correct state.

**Comment by tylerbwong** [comment]
Wow, great findings and I really appreciate all the hard work you've done here to track down the issue! This all makes sense to me, and your tests and build scans back up your claims. Will get your fixes in a new patch ASAP.

**Comment by jhansche** [comment]
Tested with 0.3.2, and it works, much faster for me, thank you.

Also faster after fixing the java_home mixup 😬 It looks like Android Studio somehow configured my gradle home directory to java home. Not sure if that was a bug in Android Studio at some point, but it was affecting multiple projects.
