### ISSUE TITLE
Missing param annotations not failing build

### ISSUE THREAD

**Issue by yschimke** [tylerbwong/metalava-gradle#62]
See https://github.com/google/horologist/pull/948

This PR changed API by adding an annotation https://github.com/google/horologist/pull/941

```
- ctor public Media(String id, String uri, String title, String artist, optional String? artworkUri, optional @ColorInt Integer? artworkColor, optional java.util.Map<java.lang.String,?> extras);
+ ctor public Media(String id, String uri, String title, String artist, optional String? artworkUri, optional Integer? artworkColor, optional java.util.Map<java.lang.String,?> extras); 
```

Regenerating APIs with (this is used locally before submitting PR) correctly adds annotation

`./gradlew metalavaGenerateSignature metalavaGenerateSignatureDebug`

But, in CI the following passes even without the change

`./gradlew metalavaCheckCompatibility metalavaCheckCompatibilityRelease`

**Comment by tylerbwong** [comment]
Hm, I'm wondering if it's passing because it doesn't consider adding an annotation a breaking API change? Does the check compatibility task still pass for a removed or added parameter?

**Comment by yschimke** [comment]
Yes, still failed for other changea

**Comment by saket** [comment]
+1 to this. I'd be interested in failing my CI checks if anything changes in my public API. Changing annotations may not be a breaking change from the POV of the compiler, but can have significant impacts at runtime.

**Comment by tylerbwong** [comment]
@liutikas I haven't gotten a chance to dive into the changes in alpha09, but is this supported? Or is it already supported?

**Comment by tylerbwong** [comment]
Currently have a CL open to add support this in the main project: https://android-review.googlesource.com/c/platform/tools/metalava/+/3139013

#95 is a sample of what the config option would look like in practice.

**Comment by tylerbwong** [comment]
This will be available in the next release.

**Comment by liutikas** [comment]
![4f5a75c02f88d6096dfe7a2c647d9fac](https://github.com/user-attachments/assets/c3ee8250-9a14-4ad7-938f-29e6a29b280f)

Thanks for the contribution to metalava!
