### ISSUE TITLE
Missing Windows Support

### ISSUE THREAD

**Issue by tylerbwong** [tylerbwong/metalava-gradle#8]
There seems to be something wrong when invoking the task from a Windows machine. As seen in https://github.com/apollographql/apollo-android/pull/2771.

**Comment by tylerbwong** [comment]
Metalava uses `:` to separate classpaths, but on Windows the drive is prepended to the path as `C:` for example which is likely not expected by Metalava.

**Comment by tylerbwong** [comment]
Need to use `File.separator` instead of hardcoding `:`.

**Comment by tylerbwong** [comment]
Should be fixed by ea4432dcd7690fcf5498e9223b2fc98a0fcd8ff6.

**Comment by tylerbwong** [comment]
This is still a problem as noted in https://github.com/apollographql/apollo-android/pull/2774.

**Comment by ludovicroland** [comment]
> This is still a problem as noted in [apollographql/apollo-android#2774](https://github.com/apollographql/apollo-android/pull/2774).

My bad! I checkout the project and launch directly the gradle task without build the project before 😇 .

Before launching the gradle task, if I build the project, it works great!

Thank you!

**Comment by tylerbwong** [comment]
Awesome! Glad to hear it's working 😃 Thanks for all the help!

**Comment by martinbonnin** [comment]
I just tried on a windows machine and could reproduce the `Failed to transform apollo-runtime.jar` error. It works well if the project is already built but fails if `metalavaGenerateSignature` is called from a vanilla project leading me to believe there's a missing dependency somewhere.

**Comment by martinbonnin** [comment]
Maybe adding something like 

```
            tasks.register(name, JavaExec::class.java) {
                input(module.compileClasspath)
```

would do it

**Comment by tylerbwong** [comment]
@martinbonnin Thanks for trying it out. I was able to reproduce this on a non-Windows machine as well so I created #9 to track this bug.
