### ISSUE TITLE
Kotlin 1.9 support

### ISSUE THREAD

**Issue by vanniktech** [tylerbwong/metalava-gradle#81]
It seems like it does not work with Kotlin 1.9. I also tried explicitly using `classpath("com.android.tools.metalava:metalava:1.0.0-alpha08")` but I think they made a change which requires you to update the way you use their API.

See here: https://github.com/vanniktech/multiplatform-locale/pull/103/commits/9396c2a492b11baf24f319780f2fa3c30c9ef2ef - it can't resolve types any more with Kotlin 1.9 when running the `metalavaGenerateSignatureDebug` task.

**Comment by yschimke** [comment]
I'm getting similar errors with error.NonExistentClass

**Comment by tylerbwong** [comment]
Just pushed an update to use `1.9.10`. Tested it on the `kotlin-1.9` branch in https://github.com/vanniktech/multiplatform-locale as well. `0.3.4` should be published shortly!

**Comment by tylerbwong** [comment]
There was an issue with the release. Looking into it.
