### ISSUE TITLE
Support 1.0.0-alpha09

### ISSUE THREAD

**Issue by herriojr** [tylerbwong/metalava-gradle#83]
Trying this version fails due to changes in metalava command line options. More specifically the visibility modifiers such as "--protected" are no longer available.

**Comment by efemoney** [comment]
@tylerbwong any reason why this didnt make it into 0.3.5?

**Comment by tylerbwong** [comment]
> @tylerbwong any reason why this didnt make it into 0.3.5?

Hi @efemoney, unfortunately no other reason than I just didn't have time to sift through the API changes and work on it. PRs welcome if anyone would like to take this on!
