### ISSUE TITLE
Plugin version 0.3.4 could not be found error

### ISSUE THREAD

**Issue by MasoudFallahpourbaee** [tylerbwong/metalava-gradle#84]
I followed the setup guide and tried to apply version 0.3.4 and got the following error:

```
Could not find me.tylerbwong.gradle.metalava:plugin:0.3.4.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/me/tylerbwong/gradle/metalava/plugin/0.3.4/plugin-0.3.4.pom
- https://repo.maven.apache.org/maven2/me/tylerbwong/gradle/metalava/plugin/0.3.4/plugin-0.3.4.pom
- https://plugins.gradle.org/m2/me/tylerbwong/gradle/metalava/plugin/0.3.4/plugin-0.3.4.pom
```

If I change the version to 0.3.3 everything works as expected.

**Comment by iamutkarshtiwari** [comment]
Facing the same issue after upgrading to 0.3.4.

**Comment by GokhanArik** [comment]
It looks like release [job](https://github.com/tylerbwong/metalava-gradle/actions/runs/6462941535/job/17545343709) failed. The project is missing the API dump for the 0.3.4 release.

**Comment by tylerbwong** [comment]
Sorry folks, working on getting 0.3.4 uploaded. Will update here once it's done.

**Comment by tylerbwong** [comment]
[0.3.5 ](https://plugins.gradle.org/plugin/me.tylerbwong.gradle.metalava/0.3.5) has been uploaded!
