### ISSUE TITLE
Access "--hide" in extension

### ISSUE THREAD

**Issue by hodgdon** [tylerbwong/metalava-gradle#92]
Would be nice to configure the extension with "--hide" options like "DeprecationMismatch".

**Comment by tylerbwong** [comment]
Since there are so many options with new ones getting added frequently, I've added a new `arguments` configuration option in [855d3ca](https://github.com/tylerbwong/metalava-gradle/commit/855d3ca93b5cff609e86149e86ac7a448c132b10) which would allow passing in "--hide" manually.
